### ISSUE TITLE
backing API appears to be down

### ISSUE THREAD

**Issue by TrooperT** [godrix/lookup-mac-anddress-chrome-extension#1]
Example:
![image](https://user-images.githubusercontent.com/1194617/206510972-b0801f70-c08b-4d5b-a971-5804416ed677.png)
Should return for PC Partners

Return alert:
![image](https://user-images.githubusercontent.com/1194617/206511212-41e73419-dc0a-477b-929c-e3908069536a.png)

Looking through the codebase, it appears https://look-mac-anddrees.herokuapp.com may be having a malfunction. Unsure if that is an application maintained by you or someone else. 

Just wanted to bring this to your attention, as this chrome extension is a great tool I use almost daily and is an amazing time-saver.

Cheers,
@TrooperT

**Comment by godrix** [comment]
Hello, recently heroku removed the free plan, I ended up forgetting it was there 🙃, I'll put it in my rodmap to fix this as soon as possible

**Comment by godrix** [comment]
There's already a correction in analysis at the store, now we just have to wait for v 3.0.
